Drupal upgrade NextGen
CivicActions/openacr pull request #18
Opened 2023-06-19 21:04 UTC by mgifford

Ok, hopefully this comes across ok.

2023-06-19 21:21 UTC, dmundra requested changes
Left a few comments.

2023-06-19 21:21 UTC, dmundra commented on openacr/drupal-10-16.yaml
> +repository: "https://github.com/GSA/openacr/blob/main/openacr/drupal-10-16.yaml"
I know we recently merged changes into GSA because of the criteria bug, but I am not sure if we can do it all the time hence why I made the canonical source the CivicActions repo. Probably best to move this into Drupal core eventually but for now do you want to try to get this into GSA asap?

2023-06-19 21:21 UTC, dmundra commented on openacr/drupal-10-16.html
Looks like this is the HTML one from the editor. Should we generate it based on the CLI tool instead?

2023-06-19 21:23 UTC, mgifford commented on openacr/drupal-10-16.html
That would probably be more consistent. I wonder how different they are.

My vote would be to commit this as it is and then I can run the command line tool in the morning and see how the results differ.

2023-06-19 21:37 UTC, dmundra approved these changes

2023-06-21 19:13 UTC, mgifford commented on openacr/drupal-10-16.yaml
> +repository: "https://github.com/GSA/openacr/blob/main/openacr/drupal-10-16.yaml"
I think it's fine to be in CA. I thought I had done this, but seems that I didn't.

2023-06-21 19:22 UTC, merged