Create 2.4-edition-wcag-2.2-en.yaml
CivicActions/openacr pull request #21
Opened 2023-08-09 14:59 UTC by mgifford

Initial PR to include 2.2

2023-08-09 16:07 UTC, maryjom commented on catalog/2.4-edition-wcag-2.2-en.yaml
> +title: VPAT® 2.4
FYI, there is already a VPAT 2.4Rev existing (for WCAG 2.1, 508, and EN 301 549 V3.2.1). When WCAG 2.2 is incorporated, this will likely be VPAT 2.5.

2023-08-11 04:44 UTC, dmundra requested changes
Thanks @mgifford for adding this. Can you build the commit from the the `main` branch instead of the `ca-main` one? This catalog will want to go into that branch.

2023-08-11 21:50 UTC, mgifford commented on catalog/2.4-edition-wcag-2.2-en.yaml
> +title: VPAT® 2.4
Thanks @maryjom I appreciate you chiming in here. Would it help to have a comment there to clarify this? Easy enough to do.

2023-08-11 21:52 UTC, mgifford commented
I'm happy to do this next week. Would be easier for me to just close this PR and submit another one (incorporating the changes requested by @maryjom ).  That make sense?

2023-08-16 02:55 UTC, dmundra commented
@mgifford it would definitely by easier to recreate this PR but I can do that if you like, let me know.

2023-08-16 20:50 UTC, dmundra commented
@mgifford created new PR #22, closing this one, feel free to add to that one.

2023-08-16 20:50 UTC, closed without merging

2023-08-16 21:22 UTC, maryjom commented on catalog/2.4-edition-wcag-2.2-en.yaml
> +title: VPAT® 2.4
@mgifford Helpful to have a comment **where** to clarify?